# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('address', models.TextField(default='')),
                ('location_x', models.FloatField(default=1000.0)),
                ('location_y', models.FloatField(default=1000.0)),
                ('phone', models.TextField(default='')),
                ('cause', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('date_of_birth', models.TextField()),
            ],
        ),
    ]
