# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegiveapp', '0004_auto_20170329_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
