# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wegiveapp', '0005_auto_20170329_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wegiveapp.Charity'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wegiveapp.Donor'),
        ),
    ]
